version: "3.9"

volumes:
  sqlite_volume:
  log_volume:

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - sqlite_volume:/usr/src/app/backend/sqlite
      - log_volume:/usr/src/app/backend/log
    ports:
      - 8000:8000
      - 8001:8001
    command: python app.py

