version: "1"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend/sqlite:/usr/src/app/backend/sqlite
      - ./backend/log:/usr/src/app/backend/log
    ports:
      - 8000:8000
      - 8001:8001


volumes:
  sqlite_volume: {}
  log_volume: {}
