version: "3.9"

volumes:
  sqlite_volume:
  log_volume:

services:
#  nginx:
#    build: ./nginx
#    container_name: nginx
#    #volumes:
#    #  - ./:/var/www
#    ports:
#      - "8001:8001"
#    networks:
#      - my-network
#    command: [nginx-debug, '-g', 'daemon off;']
#    depends_on:
#      - backend
  backend:
    build: ./backend
    container_name: backend
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "main:create_flask_app()"
    volumes:
      - sqlite_volume:/usr/src/app/sqlite
      - log_volume:/usr/src/app/var
    ports:
      - "8000:8000"
    networks:
      my-network:
        aliases:
          - backend-app


networks:
  my-network:

